<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Livraria_TI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\DTO\**" />
    <Content Remove="Models\DTO\**" />
    <EmbeddedResource Remove="Models\DTO\**" />
    <None Remove="Models\DTO\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Administrador\StyleSheet.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Images\ImgLivros\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

</Project>
