<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Livraria_TI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NovaPasta\**" />
    <Content Remove="NovaPasta\**" />
    <EmbeddedResource Remove="NovaPasta\**" />
    <None Remove="NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\Detalhe.cshtml" />
    <Content Remove="Views\Home\Detalhe.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Detalhe.cshtml.css" />
  </ItemGroup>

</Project>
